version: '3.8'

services:
  app:
    image: impostor-prod
    container_name: impostor-app-prod
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - '3000:3000'
